### ISSUE TITLE
No able to concatenate values

### ISSUE THREAD

**Issue by dgroh** [loedeman/AutoMapper#10]
Hello, I've been struggling to concatenate **firstName **+ **lastName** to a **displayName** property. I tried several approaches based on the tests, but unsuccessful. I'm pretty sure this should be straight forward, but I don#t find any references.

That is my code:

```
            automapper.createMap("UserA", "UserB")
                .forMember("displayName", (o: MemberConfigurationOptions) => {
                    o.mapFrom("firstName"); // " + " + LastName
                })
                .convertToType(User);
```

Of course I know this is never going to work, as `mapFrom` is a **void** method, but I also tried other approaches, even with the intermediatePropertyValue didn't work.

**Comment by loedeman** [comment]
Hi @dgroh, nice to know you are trying to reach goals beyond documentation ;) ... It is definitely possible to reach the goal you are trying to reach. In fact, you have a couple of options to get there. The missing link in your code is stacking forMember calls (which is the idea which automapping). Here is a sample doing the job (in JS, since I often reproduce in a small index.html file ;) ):

```
var sourceKey = 'UserA';
var destinationKey = 'UserB';

var sourceObject = { lastName: 'Doe', firstName: 'John' };
automapper
    .createMap(sourceKey, destinationKey)
    .forMember('displayName', function (opts) { return opts.mapFrom('lastName'); })
    .forMember('displayName', function (opts) { 
        return opts.sourceObject['firstName'] + ' ' + opts.sourceObject[opts.sourcePropertyName]; // or: opts.intermediatePropertyValue;
     })
    .forMember('firstName', function (opts) { return opts.ignore(); });

var result = automapper.map(sourceKey, destinationKey, sourceObject);
alert(JSON.stringify(result));
```

Cheers, Bert
