### ISSUE TITLE
Using with a project that use modules

### ISSUE THREAD

**Issue by lujop** [loedeman/AutoMapper#16]
Can you provide a sample of how to use the library in an angular project that use modules.
Does the library export any module?

**Comment by loedeman** [comment]
Hi lujop, thanks for your question. I hope you are already using AutoMapper in the configuration you asked me about. In that case, please keep me posted! 

Since v1.7.0 AutoMapper does export the AutoMapper object in a way WebPack and UMD are working. It should therefore also work for you ;) ...

Currently, I don't work with Angular myself. Are you referring to AngularJS (v1) or Angular (v2)? I am just starting a project in Angular (v2), will definitely try using AutoMapper in that one in the nearby future!

Cheers, Bert

**Comment by lujop** [comment]
No, I was not able to use it.
I tried in an Angular V2 project, but I've to say that I'm very newbie in JS , modules and Angular world.

**Comment by loedeman** [comment]
Thanks for your reply. You should have a look at issue #17. I did try using AutoMapper in Angular (v2) myself and succeeded that mission quite easily. In the mentioned issue, I documented the (minimal) steps to take for an Angular project. Of course, you can implement a module yourself to wrap the 'global' behaviour into something injectable ;)...

**Comment by grandy01** [comment]
Hello, Bert.

I'm developing a node.js server with TypeScript (2.0). I want to use your library, but I'm having trouble with importing it. I try to
`import AutoMapperJs from 'automapper-ts';`
and get "File '/home/.../node_modules/automapper-ts/dist/automapper.d.ts' is not
 a module.". Can please explain how to use the library in this case? Also, I think it would be useful to add such information to 'Getting started' guide. 

Thanks, Andrei

**Comment by loedeman** [comment]
Hi Andrei,

It makes sense why the package is not importing like you would expect it to do: I didn't create the package as a module (yet).

I am planning to make the package importable, but that takes some thorough thinking, since the package is already being used quite heavily the way it currently works... I am considering a scenario like creating a second package with source code sharing to realize the modular behavior ;) ...

In the mean time, if you just arrange the automapper.min.js file to be loaded, you should be able to use the automapper global variable (which can be used with its automapper.d.ts typing companion to have typing as well)...

Should you have plenty of time, I would be delighted if you could give me a hand :) ...

Cheers, Bert

**Comment by grandy01** [comment]
@loedeman Actually, they've switched to the instance-based behavior in C# Automapper, maybe that's the reason I was trying to import you lib as a module :)

Ok, so I assume it should work as a global variable and globally-accessed classes, but in fact it didn't work either. The compiler complained he didn't recognize the variable. Should add smth to my .tsconfig? (I assume I don't have to, but asking just in case).

Actually, I'd like to help you, but I'm only in the beginning of studying/investigating TS world, so please excuse me for my newbieness :)

**Comment by loedeman** [comment]
Lol, I know they did! I am not there yet 😀... About the automapper.d.ts file: you could try adding that one in your typing a configuration if it is not picked up automatically (in order to get typing to work). Of course you can also test if AutoMapperTS has been loaded by logging the automapper object to the console 😉...

**Comment by staff0rd** [comment]
I found this also, but in node so thought it was a regression of #7, however it seems the fix was just to add the following to the bottom of `automapper.d.ts`;

~~~javascript
export = automapper;
~~~

After doing so I was able to properly import and execute automapper tasks using the following;

~~~javascript
import automapper = require("automapper-ts")
automapper.createMap('ObjA', 'ObjB') // etc
~~~

**Comment by CiprianDraghici** [comment]
I posted a message as an workaround on stackoverflow: https://stackoverflow.com/a/53223669/7745982

**Comment by loedeman** [comment]
Thanks for your help, @cipriandraghici93 #h5yr!
