### ISSUE TITLE
Google Closure Compiler support

### ISSUE THREAD

**Issue by staff0rd** [loedeman/AutoMapper#22]
I guess it's a little obvious that this doesn't work with Google Closure Compiler, notably with `ADVANCED_OPTIMIZATIONS`, considering automapper-ts refers to types and properties via strings that will be not be changed when the compiler changes types and property names.

Any thoughts for supporting this? (or to officially not support it ;)).

**Comment by loedeman** [comment]
Hi @staff0rd,

I do not currently consider supporting the Google Closure compiler officially. 

Having that clarified: I think AutoMapperTS will just work with the Closure compiler in most cases (e.g. mapping results from REST API JSON objects). If you are intending only using AutoMapperTS in your heavily optimized application, I indeed think this won't work with for(Source)Member calls. There is no way to directly map properties up front, since there is no typing in JavaScript.

I am considering to make use of TypeScript generics in the future. However, this makes using a TypeScript precompilation step a necessity, which I am not sure of a) is something I want and b) is something which will actually work in every scenario you throw at it.

Should you have a wonderful idea about how AutoMapperTS could be perfected, please bring it on (or fork the repo and file a PR)!

Cheers, Bert
