### ISSUE TITLE
Angular 4 ng build --prod does not work

### ISSUE THREAD

**Issue by alejandrocoding** [loedeman/AutoMapper#31]
Hi @loedeman 

I could make your lib work in a Angular v4 project + CLI and it seems great!

I created a service where I am loading configurations for every module to register the mappings and then, just using automapper.map works smoothly.

However, I have the problem that if I run "ng build --prod" with the Angular CLI, all the values are coming as empty, so in a table of 7 rows, I get those 7 objects, but they are empty value.

During Environment config and without --prod flag works perfectly, no with that flag.

I know you didn't build this lib thinking on Angular project but Typescript project, but it would be nice to know your thoughts here.

I checked the scripts.bundle that cli create trhough that command and it seems to be added correctly, so no idea what could be happening.

I can create a project for you in order to recreate the error, anyway I think creating a new project with cli and adding the library would be enough, but let me know If I can help out.

Thanks,

**Comment by loedeman** [comment]
Hi @ialex90, thanks for reaching out. I would be glad if you could create a project for me to recreate the error. I am afraid I cannot fully understand your issue without it, actually ;). I am afraid the Angular optimizations kicking in when building production mode is messing up with AutoMapperTS, I am curious to discover what the actual problem is and how/if it could be fixed. Hope to hear from you soon ;)! Cheers, Bert

**Comment by lucaritossa** [comment]
I'm facing with a similar issue.  
I'm working with an angular v4 project with webpack.  

My "createMaps" are all based with a **string sourceKey** and a **classType destinationKey** pattern. The "convertToType" fluent method is not needed in this case because it automatically return my destination classType.

```
automapper.createMap('json', MyClassA);
automapper.createMap('json', MyClassB);
```
But this creates strange behaviour when using "prod" flag: wrong classes mapped.  

I finally discovered that the uglify plugin I'm using [UglifyJsPlugin is mangling](https://github.com/webpack/webpack/issues/1659) the variable "MyClass.name" used (correctly) by AutomapperHelper.getClassName method.
Unfortunately with "prod" flag more than one class returns the same class name "t" :(  

In the example above the strange behaviour was that the map of MyClassA returned a MyClassB object.  
I added "console.log(MyClassA.name)" and "console.log(MyClassB.name)" and both messages returned 't'

I'm currently using the workaround of using string as destinationKey with "convertToType(MyClass*)" fluent method.

```
automapper.createMap('json', 'MyDestinationKeyForClassA').convertToType(MyClassA);
automapper.createMap('json', 'MyDestinationKeyForClassB').convertToType(MyClassB);
```

This works for me even if I'm not so satisfied. Using strings for source and destination keys makes my code less maintenable in case of refactoring...

**Comment by nitimmerman** [comment]
Hi @lucaritossa 
Thanks for pointing this out.
You steered me in the right direction.
the webpack -p option does by default mangle your code but you can override that by specifying the uglifyjsplugin options in your webpack config file and omitting the -p option.
this solved it for me:

`  
new UglifyJSPlugin({
            cache: true,
            uglifyOptions: {
                beautify: false, //prod                       
                sourceMap: false,
                ecma: 6,
                mangle: {
                    keep_fnames: true,
                    keep_classnames:true,
                    reserved: ['$super', '$', 'exports', 'require']
                }, //prod
                compress:
                    {           
                        keep_classnames: true,
                        keep_fnames:true,
                        warnings: false,
                        conditionals: true,
                        unused: true,
                        comparisons: true,
                        sequences: true,
                        dead_code: true,
                        evaluate: true,
                        if_return: true,
                        join_vars: true,
                        negate_iife: false // we need this for lazy v8               
                    },
                output: {
                    //     space_colon: false,
                    comments: function (node, comment) {
                        var text = comment.value;
                        var type = comment.type;
                        if (type === "comment2") {
                            // multiline comment
                            return /@copyright/i.test(text);
                        }
                    }
                }
            }
        })
`
