### ISSUE TITLE
definitly typed

### ISSUE THREAD

**Issue by klaasjs** [loedeman/AutoMapper#5]
The typedefinitions are not available at https://github.com/DefinitelyTyped/DefinitelyTyped. Is there any chance they are added to the definitelytyped repository in the future?

**Comment by loedeman** [comment]
Hi klaasjs,

It appears the DefinitelyTyped library is pretty crowded and it's not that easy to get your type definitions in there. When using Bower or NPM, the definition file is delivered to the client and can be used in a controlled manner. That's why we did not perform a really serious attempt to get it there. Should you really want the definition file to be in the DefinitelyTyped repo, I would like to challenge you to get it in there yourself (I would sure be very thankful ;)).

Cheers, Bert

**Comment by klaasjs** [comment]
Hi Bert,

I'll try to get it in there because now my build system has to refer to ./typings/**/*.d.ts and ./bower_components/arcady-automapper/arcady-automapper.d.ts'. I rather have it all in ./typings :) I will keep you up to date of my progress.

Klaas

**Comment by loedeman** [comment]
Thanks a lot, Klaas!

**Comment by loedeman** [comment]
Hi Klaas, did you make any progress publishing the AutoMapper type definition file to the DefinitelyTyped repository? Cheers, Bert

**Comment by klaasjs** [comment]
Hi Bert,

I'm stuck with the travis part in the [contribution guide](http://definitelytyped.org/guides/contributing.html). I then tried the tsd link feature which let's you add some custom configuration to (apparently) package.json or bower.json but this also didn't work like expected. Work in progress..

Klaas

**Comment by loedeman** [comment]
Klaas, I am closing this issue for stats sake ;) ... I will leave the comments open, should you be succesful adding the definition files to the DefinitelyTyped repository, please comment on this issue ;) ...

**Comment by klaasjs** [comment]
will do!
