### ISSUE TITLE
Several pages on the wiki are not accessible

### ISSUE THREAD

**Issue by ghost** [loedeman/AutoMapper#50]
The following wiki pages redirect to the home wiki page with an error "You do not have permission to update this wiki"

- Mapping performance
- Validation (assertConfigurationIsValid)
- Naming conventions
- Asynchronous mapping
- Flattening and nesting

The permissions should be updated so we can view the documentation for these features.

**Comment by loedeman** [comment]
Hi @heilc,

I am afraid those wiki pages have been thought about a long time ago, but I simply forgot to write any actual content... Since I am very busy on my day time job, I am afraid I will not be able to resolve this any time soon.

Mapping performance measuring and mapping validation have been implemented in a very (!) basic way. I got asked about those two once, but there seems not to be a lot of requests to further invest in those topics. 

The best I can offer you right now is to point to the unit tests covering the last three topics...

Cheers, Bert

**Comment by ghost** [comment]
Thanks for responding! That makes sense. I would make one request then based on your reply. Could you create an empty page with a generic "TODO" or something along those lines? It would avoid confusion in the future, and if someone out there wants they could create a PR and add content themselves

**Comment by loedeman** [comment]
Hi @heilc, thanks for your suggestion. Those pages have been created ;) . Of course, a PR would also be welcome :) . Cheers!
