### ISSUE TITLE
Nested properties in array

### ISSUE THREAD

**Issue by Duskfall** [loedeman/AutoMapper#6]
Hello i would like to ask you how is it possible to map from an Array a nested property to a model.
Example:

    var foos = [ { type : { id : 1, name :  "test" } , spec :  { id : 1, name :  "test" } },
                        { type : { id : 1, name :  "test" } , spec :  { id : 1, name :  "test" } } 
                     ];

    //var myWantedModel : { type : foos[0].type.name } for example

If i try the mapper with forMember i get returned an array with the initial data.
If i use convertUsing :

    .convertUsing(function (resolutionContext) {
                    return { type: resolutionContext.sourceValue.type.name, spec: resolutionContext.sourceValue.spec.name };
              });

I get an array with 2 empty objects

**Comment by loedeman** [comment]
Hi Duskfall, 

Currently, this is not possible with AutoMapper. Every conversion is performed on the single item level. You could of course map from a source array to a destination array (this is supported out of the box) and afterwards combine the results into one object. Does this help you? Otherwise, could you please specify which business need you try to cover? If creating support for your business need is doable and feasibly, we can always try adding this kind of functionality ;) ...

Cheers, Bert

**Comment by Duskfall** [comment]
Hi @loedeman  thanks for reply, i want to map a business logic dto which is different than my UI model!
I managed to do this chaining the mapping

    .forMember('type', function (opts) { return opts.sourceObject.type ? opts.sourceObject.type.name : null })
    .forMember('uiType', (opts) => opts.mapFrom('type'))
    .forMember('uiType', (opts) => {return opts.sourceObject.type.name })

Dto is an object with type property, which is and object and has an id and name properties.
I wanted to map the name property to one upper level to simplify logic.

Thanks anyway :)

**Comment by loedeman** [comment]
Hi @Duskfall, thanks for clarification. Do I understand you completely, when I consider the following code as the solution you originally would have wanted to have?

```
.forMember('uiType', (opts) => opts.mapFrom('type.name'))
```

This syntax does feel 'right' to me as well, it should not be very hard to get it working too... If this code would be helpful, I will give it a try ;) ...

**Comment by Duskfall** [comment]
Yeah exactly! In MVC we have this syntax for this kind of case
ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type.Name));

**Comment by loedeman** [comment]
Hi @Duskfall, you should now be able to use nested mapping. It has been more of a hassle than I initially expected, but everything works on my end now (you could have a look at the unit tests if you like). There is some work to do in order to get the code nicer and smoother, but I do not expect the functionality to be buggy...

PS. The package has been relocated and renamed though, I would be pleased if you would give the brand new AutoMapperTS v1.6.0 a try ;) ...

**Comment by Duskfall** [comment]
Just tested it and worked fine! Cheers!

**Comment by rasikas** [comment]
Im not sure what Im doing wrong here, but I still get an array with empty objects. when using `convertUsing()`
