### ISSUE TITLE
Using AutoMapper Angular 7 Error: Unable to extract class name from type 'undefined'

### ISSUE THREAD

**Issue by misaelsz** [loedeman/AutoMapper#61]
After i follow all steps on this issue Using AutoMapper in Angular2 #17. the follwing error occurs.
![image](https://user-images.githubusercontent.com/29647393/61963426-ecdcce80-afa1-11e9-99fa-bdbd9f2dde02.png)

**Comment by misaelsz** [comment]
Issue #7 resolved the problem.

**Comment by rushisharma** [comment]
Is it necessary to assign blank values in string parameter of class?

Because it is not mapping parameters that are string without assign default values in it.

for ex,

not mapping when class is,

class destination {
id : string,
name :string,
address :string
}

we need to assign default values like,

class destination {
id : string='',
name :string='',
address :string=''
}

Any solution so that we don't need to assign default values?
